### ISSUE TITLE
Is it possible to call a callback in any thread?

### ISSUE THREAD

**Issue by matheuscscp** [bengl/sbffi#1]
Is it possible to call a callback in any thread?

**Comment by bengl** [comment]
It should work! That being said, I haven't added a test for this yet. Callbacks are done using `napi_threadsafe_function` in order to enable this, so if it *doesn't* work, that's a bug.

**Comment by bengl** [comment]
I'm going to close this since it seems your question is answered. Feel free to re-open if you think that's needed.
