### ISSUE TITLE
Port to TypesScript

### ISSUE THREAD

**Issue by JohnDeved** [bengl/sbffi#11]
hey, I really like this project. but it would really be beneficial to many node.js developers if this project was written in TypeScript, or at least would come with typescript definition files.

seeing how the js lib part of this project is only 250 lines of code, I'm willing to fork and port it if wanted.

**Comment by bengl** [comment]
I'm not interested in porting, and would like to avoid definition files. If TypeScript-supported JSDoc would be sufficient, I'd be happy to accept a PR adding that.
