### ISSUE TITLE
sbffi on Windows machine

### ISSUE THREAD

**Issue by zinji** [bengl/sbffi#2]
I am interested in using this module for calling Delphi 32 stdcall DLL on windows. My question are does this module work on windows platform and would it be possible to have few more examples of various data type use in calling the dll

**Comment by bengl** [comment]
Right now the tests are passing on Windows, so I suspect this would work fine there. The only issue I might expect is that right now `sbffi` only supports 64-bit pointers. I'm not sure what "Delphi 32" means, but if that's an issue, it might be incompatible for now.
