### ISSUE TITLE
dlLoadLibrary null support

### ISSUE THREAD

**Issue by toonvd** [bengl/sbffi#7]
According to https://www.dyncall.org/docs/manual/manualse10.html the libpath in `dlLoadLibrary` should also support `NULL`.
At the moment this barfs on https://github.com/bengl/sbffi/blob/master/src/sbffi_dynload.c#L6. Would fixing this allow for the same functionality as `null` for a libpath in ffi?

**Comment by bengl** [comment]
I've made the change allowing for `null` libpath in 7c2fdab550f8d2dfb38ccbf126f815bd8f699aee which is now on master.

**Comment by toonvd** [comment]
Going to test tonight! Thank you in advance!

**Comment by toonvd** [comment]
Tested / working, awesome!
